Patch 1
Gorialis/jishaku pull request #136
Opened 2021-11-16 23:24 UTC by BobDotCom

This allows base command to discover forks as well. Forks that change the import name will obviously not work, but that's their fault.
No breaking changes here, just improvements.

## Rationale

This just lets the base command find the name of the discord module instead of setting it to discord.py. 
Before:

![Screen Shot 2021-11-16 at 4 53 29 PM](https://user-images.githubusercontent.com/71356958/142079119-56b8bb31-f4bb-4d6b-8514-1799c985df15.png)

After:

![Screen Shot 2021-11-16 at 4 54 30 PM](https://user-images.githubusercontent.com/71356958/142079232-27a859e7-9147-49f5-888f-47a68d037631.png)

## Summary of changes made

1. Adds `importlib_metadata>=3.7.0` to the requirements. The required function, `packages_distributions`, was [added in 3.7](https://github.com/python/importlib_metadata/blob/main/CHANGES.rst#v370).
2. Changed the package name/version in the root command to be discovered from the package name instead of statically "discord.py"

## Checklist

- [x] This PR changes the jishaku module/cog codebase
    - [ ] These changes add new functionality to the module/cog
    - [x] These changes fix an issue or bug in the module/cog
    - [x] I have tested that these changes work on a production bot codebase
    - [x] I have tested these changes against the CI/CD test suite
    - [ ] ~~I have updated the documentation to reflect these changes~~ No need, only bugfixes
- [ ] This PR changes the CI/CD test suite
    - [ ] I have tested my suite changes are well-formed (all tests can be discovered)
    - [ ] These changes adjust existing test cases
    - [ ] These changes add new test cases
- [ ] This PR changes prose (such as the documentation, README or other Markdown/RST documents)
    - [ ] I have proofread my changes for grammar and spelling issues
    - [ ] I have tested that any changes regarding Markdown/RST syntax result in a well formed document

2021-11-17 00:43 UTC, Gorialis requested changes

2021-11-17 00:43 UTC, Gorialis commented on jishaku/features/root_command.py
> +from importlib_metadata import packages_distributions
```suggestion
try:
    from importlib.metadata import packages_distributions
except ImportError:
    from importlib_metadata import packages_distributions
```

2021-11-17 00:43 UTC, Gorialis commented on requirements/_.txt
> +importlib_metadata>=3.7.0
```suggestion
importlib_metadata>=3.7.0; python_version<"3.10"
```

2021-11-18 13:59 UTC, BobDotCom commented
Changes implemented

2021-11-18 15:09 UTC, Gobot1234 commented
This version constrain is wrong it should be for <3.8 not 3.10

2021-11-18 15:21 UTC, BobDotCom commented
> This version constrain is wrong it should be for <3.8 not 3.10

`importlib.metadata` was added to the python builtins in 3.8 with features from importlib_metadata version 1.4. Since we need a feature from importlib_metadata 3.7, python 3.10 is correct because importlib_metadata 4.4 features were added to python in 3.10.
![Screen Shot 2021-11-18 at 9 21 09 AM](https://user-images.githubusercontent.com/71356958/142443722-dcfb6796-32b4-49cb-a1f7-64d69c05a796.png)

2021-11-18 15:23 UTC, Gobot1234 commented
Sorry I completely misread the version constraint not realising that the version numbers weren't related to python versions

2021-11-20 04:22 UTC, merged