Update get_translated_payload method in ManagementFeature
Gorialis/jishaku pull request #230
Opened 2024-04-13 00:42 UTC by Vioshim

## Rationale

The function requires the bot's tree for working accordingly

## Summary of changes made

It adds bot.tree as parameter for the function

## Checklist

- [x] This PR changes the jishaku module/cog codebase
    - [ ] These changes add new functionality to the module/cog
    - [x] These changes fix an issue or bug in the module/cog
    - [x] I have tested that these changes work on a production bot codebase
    - [x] I have tested these changes against the CI/CD test suite
    - [ ] I have updated the documentation to reflect these changes
- [ ] This PR changes the CI/CD test suite
    - [ ] I have tested my suite changes are well-formed (all tests can be discovered)
    - [ ] These changes adjust existing test cases
    - [ ] These changes add new test cases
- [ ] This PR changes prose (such as the documentation, README or other Markdown/RST documents)
    - [ ] I have proofread my changes for grammar and spelling issues
    - [ ] I have tested that any changes regarding Markdown/RST syntax result in a well formed document

2024-04-16 14:27 UTC, Gorialis commented
The function signature doesn't indicate that this should be necessary. Can you explain why you thought this change was necessary (and ideally include any supporting errors or other info you can about what lead you towards this fix)?

2024-04-16 14:36 UTC, Vioshim commented
![image](https://github.com/Gorialis/jishaku/assets/63890837/350b4edf-1d59-4067-a56d-2508975eb971)

It errors, but now that I look properly into source code, it has to do with how it works for hybrid commands.
https://github.com/Rapptz/discord.py/blob/425edd2e10b9be3d7799c0df0cd1d43a1a34654e/discord/app_commands/transformers.py#L93, as hybrid commands require the tree and the translator. (Therefore this PR breaks normal app commands, so please don't merge)

2024-04-16 14:43 UTC, Gorialis commented
I see. Part of how this code works might need to be rewritten to make it support both cases, I haven't really used hybrid commands so I guess I've never run into this. I imagined there might be some need to refine and update the sync procedure anyway since it deviates from how the discord.py public API intends for the sake of better diagnostics, so I'll probably need to make some kind of test harness to make sure I'm not missing things when maintaining it.

2024-04-16 14:46 UTC, tuna2134 commented
https://github.com/Rapptz/discord.py/blob/425edd2e10b9be3d7799c0df0cd1d43a1a34654e/discord/ext/commands/hybrid.py#L299

2024-04-16 14:47 UTC, tuna2134 commented
https://github.com/Rapptz/discord.py/blob/425edd2e10b9be3d7799c0df0cd1d43a1a34654e/discord/app_commands/tree.py#L1060

2024-04-16 14:48 UTC, tuna2134 commented
I am looking tree.sync function, it looks same.
And I have never seen that report

2024-04-27 01:22 UTC, pythonmcpi commented
@Gorialis fyi, this issue is only present in the (currently experimental) feature/user_apps branch of discord.py.

This is caused by a change in `app_commands.Command.to_dict`'s signature, where a new `tree` argument was added. [Permalink to the change](https://github.com/Rapptz/discord.py/blame/08b138cc71fea5594c068082ee565a05cde2c7fa/discord/app_commands/commands.py#L776) | [Link to latest feature/user_apps commit](https://github.com/Rapptz/discord.py/blame/feature/user_apps/discord/app_commands/commands.py#L776)

2024-04-27 01:25 UTC, pythonmcpi requested changes

2024-04-27 01:25 UTC, pythonmcpi commented on jishaku/features/management.py
>                  payload = [command.to_dict() for command in slash_commands]
The `to_dict()` call on line 244 also needs to be passed the tree as an argument.

2024-05-05 04:26 UTC, Vioshim commented
Change has been merged in master, jishaku's sync command no longer works with [Master Branch](https://github.com/Rapptz/discord.py/commit/2e2f51fd5c95b3c40fd1c67ae4b08bbeeaeaddce#diff-edc6201f259e50254d3bc72339d8935f50a795fee7f4f0056c31e0641635c493R1740)

2024-05-08 03:25 UTC, JDJGInc commented
Can confirm:
```python
May 07 23:24:59 contabo-vps python[1054883]:     ret = await coro(*args, **kwargs)
May 07 23:24:59 contabo-vps python[1054883]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 07 23:24:59 contabo-vps python[1054883]:   File "/home/jdjg/JDBot/.venv/lib/python3.11/site-packages/jishaku/features/management.py", line 246, in jsk_sync
May 07 23:24:59 contabo-vps python[1054883]:     payload = [command.to_dict() for command in slash_commands]
May 07 23:24:59 contabo-vps python[1054883]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 07 23:24:59 contabo-vps python[1054883]:   File "/home/jdjg/JDBot/.venv/lib/python3.11/site-packages/jishaku/features/management.py", line 246, in <listcomp>
May 07 23:24:59 contabo-vps python[1054883]:     payload = [command.to_dict() for command in slash_commands]
May 07 23:24:59 contabo-vps python[1054883]:                ^^^^^^^^^^^^^^^^^
May 07 23:24:59 contabo-vps python[1054883]: TypeError: Command.to_dict() missing 1 required positional argument: 'tree'
```

2024-05-14 13:02 UTC, Gorialis commented
Because this change still hasn't hit PyPI release, this PR can't be merged until it is ensured that this change doesn't break users who aren't on master branch.

2024-05-18 20:13 UTC, Soheab commented
> Because this change still hasn't hit PyPI release, this PR can't be merged until it is ensured that this change doesn't break users who aren't on master branch.

It could handle the error? If this gets merged, it will error for dpy <2.4 users anyways.

2024-06-24 18:42 UTC, Gorialis commented
Superceded by #235

2024-06-24 18:42 UTC, closed without merging